version: "3.8"
services:
  api:
    build: .
    container_name: bolsa-api-nest
    command: ["node", "dist/main.js"]
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: bolsa-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: bolsa_sim
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
